<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Trykatch.Modules.Federation.Domain/Trykatch.Modules.Federation.Domain.csproj" />
    <ProjectReference Include="../Trykatch.Modules.Federation.IntegrationEvents/Trykatch.Modules.Federation.IntegrationEvents.csproj" />
  </ItemGroup>
</Project>
