// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trykatch.Infrastructure.Persistence;

#nullable disable

namespace Trykatch.Infrastructure.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trykatch.Domain.Organizations.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectDisplayName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OccurredAt");

                    b.ToTable("audit_entries", "platform");
                });

            modelBuilder.Entity("Trykatch.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExhaustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastErrorType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReplayGeneration")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "ExhaustedAt", "OccurredAt", "Id");

                    b.ToTable("outbox_messages", "platform");
                });

            modelBuilder.Entity("Trykatch.Infrastructure.Persistence.OutboxReplayRequest", b =>
                {
                    b.Property<Guid>("RequestId").HasColumnType("uuid");
                    b.Property<Guid>("ActorId").HasColumnType("uuid");
                    b.Property<int>("ExpectedFailedGeneration").HasColumnType("integer");
                    b.Property<Guid>("MessageId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("RequestedAt").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("CURRENT_TIMESTAMP");
                    b.HasKey("RequestId");
                    b.HasIndex("RequestedAt", "RequestId");
                    b.ToTable("outbox_replay_requests", "platform", t =>
                        t.HasCheckConstraint("CK_outbox_replay_requests_generation", "\"ExpectedFailedGeneration\" >= 0"));
                });

            modelBuilder.Entity("Trykatch.Infrastructure.Persistence.OutboxRecoveryEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("MessageId").HasColumnType("uuid");
                    b.Property<int>("ReplayGeneration").HasColumnType("integer");
                    b.Property<string>("Outcome").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
                    b.Property<Guid?>("ActorId").HasColumnType("uuid");
                    b.Property<string>("FailureCode").HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<string>("FailureType").HasMaxLength(240).HasColumnType("character varying(240)");
                    b.Property<DateTimeOffset>("OccurredAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid?>("RequestId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("MessageId", "ReplayGeneration", "Outcome").IsUnique().HasFilter("\"Outcome\" = 'terminal'");
                    b.HasIndex("OccurredAt", "MessageId", "ReplayGeneration");
                    b.HasIndex("RequestId").IsUnique().HasFilter("\"RequestId\" IS NOT NULL");
                    b.ToTable("outbox_recovery_events", "platform", t =>
                    {
                        t.HasCheckConstraint("CK_outbox_recovery_events_generation", "\"ReplayGeneration\" >= 0");
                        t.HasCheckConstraint("CK_outbox_recovery_events_outcome", "\"Outcome\" IN ('terminal', 'replayed', 'not_found', 'not_exhausted', 'stale_generation')");
                        t.HasCheckConstraint("CK_outbox_recovery_events_terminal", "(\"Outcome\" = 'terminal' AND \"RequestId\" IS NULL AND \"ActorId\" IS NULL AND \"FailureCode\" IS NOT NULL AND \"FailureType\" IS NOT NULL) OR (\"Outcome\" <> 'terminal' AND \"RequestId\" IS NOT NULL AND \"ActorId\" IS NOT NULL AND \"FailureCode\" IS NULL AND \"FailureType\" IS NULL)");
                    });
                });

            modelBuilder.Entity("Trykatch.Modules.Documents.Domain.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.ToTable("documents", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Trykatch.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name");

                    b.ToTable("projects", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
