<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <AspireUseCliBundle>false</AspireUseCliBundle>
    <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
    <DefineConstants Condition="'$(FlatpackUi)' == 'react'">$(DefineConstants);FLATPACK_REACT</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FlatpackApp.Api/FlatpackApp.Api.csproj" AspireProjectMetadataTypeName="TemplateProjectIdentifier_Api" />
    <ProjectReference Include="../FlatpackApp.Migrator/FlatpackApp.Migrator.csproj" AspireProjectMetadataTypeName="TemplateProjectIdentifier_Migrator" />
  </ItemGroup>
</Project>
