<Project>
  <PropertyGroup Condition="'$(IsCompositeModulePackage)' == 'true'">
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeModuleProjectOutputs</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <Target Name="IncludeModuleProjectOutputs"
          DependsOnTargets="BuildOnlySettings;ResolveReferences"
          Condition="'$(IsCompositeModulePackage)' == 'true'">
    <ItemGroup>
      <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)"
                            Condition="'%(ReferenceCopyLocalPaths.ReferenceSourceTarget)' == 'ProjectReference' and $([System.String]::Copy('%(ReferenceCopyLocalPaths.Filename)').StartsWith('Trykatch.Modules.'))">
        <TargetPath>%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</TargetPath>
      </BuildOutputInPackage>
    </ItemGroup>
  </Target>
</Project>
