<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Shouldly" />
    <ProjectReference Include="../../../../src/Modules/Documents/Trykatch.Modules.Documents.Domain/Trykatch.Modules.Documents.Domain.csproj" />
    <ProjectReference Include="../../../../src/Modules/Documents/Trykatch.Modules.Documents.Infrastructure/Trykatch.Modules.Documents.Infrastructure.csproj" />
    <Compile Include="../../../ArchitectureTestSettings.cs" Link="MSTestSettings.cs" />
  </ItemGroup>
</Project>
