<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TrykatchApp.Api/TrykatchApp.Api.csproj" />
    <ProjectReference Include="../../src/TrykatchApp.ServiceDefaults/TrykatchApp.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
