// Generated by 'flatpack module generate'. Do not edit by hand.
import { FlatpackWebModuleCatalog } from '@flatpackapp/module-sdk'
import { projectsModule } from './features/projects/module'
import { gettingStartedModule } from '@flatpackapp/module-getting-started'
import { workspaceOverrides } from './module-overrides'

export const workspaceModules = new FlatpackWebModuleCatalog([
  projectsModule,
  gettingStartedModule,
], workspaceOverrides)
