<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/FlatpackApp.Application/FlatpackApp.Application.csproj" />
    <ProjectReference Include="../../src/FlatpackApp.Domain/FlatpackApp.Domain.csproj" />
    <ProjectReference Include="../../src/FlatpackApp.Infrastructure/FlatpackApp.Infrastructure.csproj" />
    <ProjectReference Include="../../src/FlatpackApp.Modules.Abstractions/FlatpackApp.Modules.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
