// <auto-generated />
// Generated by 'flatpack module generate'. Do not edit by hand.
using FlatpackApp.Infrastructure.Modules;
using FlatpackApp.Modules.GettingStarted;
using FlatpackApp.Modules;

namespace FlatpackApp.Migrator.Modules;

internal static class EnabledModules
{
    public static IReadOnlyList<IFlatpackModule> All { get; } =
    [
        new ProjectsModule(),
        new GettingStartedModule(),
    ];
}
