// Generated by the module tool. Do not edit by hand.
import { WebModuleCatalog } from '@trykatch/module-sdk'
import { projectsModule } from '@trykatch-modules/projects'
import { documentsModule } from '@trykatch-modules/documents'
import { workspaceOverrides } from './module-overrides'

export const workspaceModules = new WebModuleCatalog([
  projectsModule,
  documentsModule,
], workspaceOverrides)
