// Generated by 'trykatch module generate'. Do not edit by hand.
import { TrykatchWebModuleCatalog } from '@trykatchapp/module-sdk'
import { projectsModule } from './features/projects/module'
import { documentsModule } from '@trykatch-modules/documents'
import { workspaceOverrides } from './module-overrides'

export const workspaceModules = new TrykatchWebModuleCatalog([
  projectsModule,
  documentsModule,
], workspaceOverrides)
