<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Trykatch.Modules.Federation</PackageId>
    <Version>1.0.0</Version>
    <Description>OIDC federation module for Trykatch applications.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
    <IsCompositeModulePackage>true</IsCompositeModulePackage>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Trykatch.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Common/Trykatch.Modules.Abstractions/Trykatch.Modules.Abstractions.csproj" PrivateAssets="all" />
    <ProjectReference Include="../../../Common/Trykatch.Modules.AspNetCore/Trykatch.Modules.AspNetCore.csproj" PrivateAssets="all" />
    <ProjectReference Include="../Trykatch.Modules.Federation.Application/Trykatch.Modules.Federation.Application.csproj" PrivateAssets="all" />
    <ProjectReference Include="../Trykatch.Modules.Federation.Domain/Trykatch.Modules.Federation.Domain.csproj" PrivateAssets="all" />
    <ProjectReference Include="../Trykatch.Modules.Federation.IntegrationEvents/Trykatch.Modules.Federation.IntegrationEvents.csproj" PrivateAssets="all" />
    <ProjectReference Include="../Trykatch.Modules.Federation.Presentation/Trykatch.Modules.Federation.Presentation.csproj" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../try&#x6B;atch.module.json" Pack="true" PackagePath="content/try&#x6B;atch.module.json" />
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
