// <auto-generated />
// Generated by the module tool. Do not edit by hand.
using Trykatch.Modules.Projects.Infrastructure;
using Trykatch.Modules.Documents.Infrastructure;
using Trykatch.Modules;

namespace Trykatch.Api.Modules;

public static class EnabledModules
{
    public static IReadOnlyList<IModule> All { get; } =
    [
        new ProjectsModule(),
        new DocumentsModule(),
    ];
    public static IReadOnlyList<InstalledDataResource> InstalledDataResources { get; } =
    [
        new("documents", new("documents", "app", "documents", ModuleDataOwnership.Organization, "Trykatch.Modules.Documents.Domain.DocumentRecord", "documents_organization_isolation", null)),
        new("projects", new("projects", "app", "projects", ModuleDataOwnership.Organization, "Trykatch.Modules.Projects.Domain.Project", "projects_organization_isolation", null)),
    ];
}
