<?xml version="1.0" encoding="utf-8"?><Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Common/Trykatch.Identity/Trykatch.Identity.csproj" />
    <ProjectReference Include="../../Common/Trykatch.Infrastructure/Trykatch.Infrastructure.csproj" />
    <ProjectReference Include="../../Common/Trykatch.Modules.Abstractions/Trykatch.Modules.Abstractions.csproj" />
    <ProjectReference Include="../../Modules/Projects/Trykatch.Modules.Projects.Infrastructure/Trykatch.Modules.Projects.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Documents/Trykatch.Modules.Documents.Infrastructure/Trykatch.Modules.Documents.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Federation/Trykatch.Modules.Federation.Infrastructure/Trykatch.Modules.Federation.Infrastructure.csproj" />
  </ItemGroup>
</Project>
