<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory Condition="'$(TrykatchUi)' == 'react'">$(MSBuildProjectDirectory)/../../web/packages/api-client/openapi</OpenApiDocumentsDirectory>
    <OpenApiDocumentsDirectory Condition="'$(TrykatchUi)' == 'none'">$(BaseIntermediateOutputPath)openapi</OpenApiDocumentsDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../TrykatchApp.Application/TrykatchApp.Application.csproj" />
    <ProjectReference Include="../TrykatchApp.Infrastructure/TrykatchApp.Infrastructure.csproj" />
    <ProjectReference Include="../TrykatchApp.Identity/TrykatchApp.Identity.csproj" />
    <ProjectReference Include="../TrykatchApp.Modules.Abstractions/TrykatchApp.Modules.Abstractions.csproj" />
    <ProjectReference Include="../TrykatchApp.Modules.AspNetCore/TrykatchApp.Modules.AspNetCore.csproj" />
    <ProjectReference Include="../TrykatchApp.Modules.Federation/TrykatchApp.Modules.Federation.csproj" />
    <ProjectReference Include="../TrykatchApp.ServiceDefaults/TrykatchApp.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
