// <auto-generated />
// Generated by 'trykatch module generate'. Do not edit by hand.
using TrykatchApp.Infrastructure.Modules;
using TrykatchApp.Modules;

namespace TrykatchApp.Migrator.Modules;

internal static class EnabledModules
{
    public static IReadOnlyList<ITrykatchModule> All { get; } =
    [
        new ProjectsModule(),
    ];
}
