// <auto-generated />
// Generated by 'trykatch module generate'. Do not edit by hand.
using TrykatchApp.Infrastructure.Modules;
using Trykatch.Modules.Documents;
using TrykatchApp.Modules;

namespace TrykatchApp.Migrator.Modules;

public static class EnabledModules
{
    public static IReadOnlyList<ITrykatchModule> All { get; } =
    [
        new ProjectsModule(),
        new DocumentsModule(),
    ];
    public static IReadOnlyList<TrykatchInstalledDataResource> InstalledDataResources { get; } =
    [
        new("documents", new("documents", "app", "documents", TrykatchDataOwnership.Organization, "Trykatch.Modules.Documents.DocumentRecord", "documents_organization_isolation", null)),
        new("projects", new("projects", "app", "projects", TrykatchDataOwnership.Organization, "TrykatchApp.Domain.Projects.Project", "projects_organization_isolation", null)),
    ];
}
