<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    <!--#if (email) -->
    <PackageReference Include="MailKit" />
    <!--#endif -->
    <!--#if (storage) -->
    <PackageReference Include="AWSSDK.S3" />
    <!--#endif -->
    <!--#if (documents) -->
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="PDFsharp-MigraDoc" />
    <!--#endif -->
    <!--#if (images) -->
    <PackageReference Include="SkiaSharp" />
    <!--#endif -->
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FlatpackApp.Application/FlatpackApp.Application.csproj" />
  </ItemGroup>
</Project>
